easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\User
        - App\Entity\Location
        - App\Entity\City
        - App\Entity\LocationsCollection
        - App\Entity\Settings
        - App\Entity\Luggage
